### ISSUE TITLE
Readme nedds to be updated

### ISSUE THREAD

**Issue by ChaoticPlex** [raiderrobert/django-css-grid#1]
Hi, 

Thank you for your useful package. I think you need to update the README file and change 
"from cssgrid import CSSGridMixin" 
to 
"from css_grid.views import CSSGridMixin"

Correct me if I am wrong, thanks.

**Comment by raiderrobert** [comment]
@ExpertNET good call! Thanks for the catch on the typo!

**Comment by raiderrobert** [comment]
Fixed in https://github.com/raiderrobert/django-css-grid/commit/0187dc2d0b6d90eed380f577444665f2f7dcdf2b
